name: PDF book generation
on:
  push:    
    tags:
      - 'v*'
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: create file list
        id: files_list
        run: |
          mkdir output  # create output dir
          echo "Listing all Markdown files..."
          echo "files=$(find . -type f -name "*.md" | sort | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - uses: docker://pandoc/latex:3.5
        with:
          args: --output=output/result.pdf ${{ steps.files_list.outputs.files }} --resource-path=./ce-1103/images:./ce-2103/images              

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: output/result.pdf
          asset_name: DSA${{ github.ref }}.pdf
          asset_content_type: application/pdf
